apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-proxy
  labels:
    app: application
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-proxy
  template:
    metadata:
      labels:
        app: node-proxy
    spec:
      containers:
        - name: internal-app
          image: internal-app-image
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: port
              value: "8080"

        - name: express-proxy
          image: express-proxy-image
          imagePullPolicy: Never
          ports:
            - containerPort: 80
          env:
            - name: SRV_NAME
              value: "express-proxy-application"
            - name: PORT
              value: "80"
            - name: TARGET
              value: "http://localhost:8080"
