apiVersion: skaffold/v2beta29
kind: Config
deploy:
  kubectl:
    manifests:
      - ./deploy.yml
      - ./service.yml
build:
  local:
    push: false
  artifacts:
    - image: internal-app-image
      context: internal-app
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: .
            dest: .
    - image: express-proxy-image
      context: express-proxy
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: .
            dest: .
